---
# tasks file for roles/ec2_stop

- block:

  - name: stop_master
    ec2:
      wait: yes
      instance_tags:
        Name: "{{item.name}}"
      region: "{{ec2_region}}"
      state: "stopped"
    with_items: "{{ec2_masters}}"

  - name: stop_slaves
    ec2:
      instance_tags:
        Name: "{{item.name}}"
      region: "{{ec2_region}}"
      state: "stopped"
    with_items: "{{ec2_slaves}}"

  tags:
    - ec2_create

  vars:
    ansible_python_interpreter: "{{ansible_env.VIRTUAL_ENV}}/bin/python"
