---
# tasks file for roles/ec2_start

- block:

  - name: start_master
    ec2:
      wait: yes
      instance_tags:
        Name: "{{item.name}}"
      region: "{{ec2_region}}"
      state: "running"
    with_items: "{{ec2_masters}}"
    register: "masters_info"

  - name: start_slaves
    ec2:
      instance_tags:
        Name: "{{item.name}}"
      region: "{{ec2_region}}"
      state: "running"
    with_items: "{{ec2_slaves}}"
    register: "slaves_info"

  tags:
    - ec2_start

  vars:
    ansible_python_interpreter: "{{ansible_env.VIRTUAL_ENV}}/bin/python"

# vim: et ts=2 sw=2:
