---
# tasks file for roles/ec2_create

- block:

  - name: create_masters
    ec2:
      key_name: "{{ec2_create_key_name}}"
      instance_type: "{{ec2_create_itype}}"
      image: "{{ec2_create_image}}"
      wait: yes
      group_id: "{{ec2_create_sec_group_ids}}"
      vpc_subnet_id: "{{ec2_create_vpc_subnet}}"
      assign_public_ip: "{{item.pubip}}"
      region: "{{ec2_region}}"
      exact_count: 1
      private_ip: "{{item.ip}}"
      instance_tags:
        Name: "{{item.name}}"
      count_tag:
        Name: "{{item.name}}"
    with_items: "{{ec2_masters}}"
    register: "masters_info"

  - name: create_slaves
    ec2:
      key_name: "{{ec2_create_key_name}}"
      instance_type: "{{ec2_create_itype}}"
      image: "{{ec2_create_image}}"
      wait: yes
      group_id: "{{ec2_create_sec_group_ids}}"
      vpc_subnet_id: "{{ec2_create_vpc_subnet}}"
      assign_public_ip: "{{item.pubip}}"
      region: "{{ec2_region}}"
      exact_count: 1
      private_ip: "{{item.ip}}"
      instance_tags:
        Name: "{{item.name}}"
      count_tag:
        Name: "{{item.name}}"
    with_items: "{{ec2_slaves}}"
    register: "slaves_info"

  - name: print_master_debugs
    debug:
      var: "{{ masters_info.results }}"
    when: ec2_debug

  - name: print_slave_debugs
    debug:
      msg: "{{ slaves_info.results }}"
    when: ec2_debug

  - name: make_out_dir
    file:
      path: "/tmp/ec2_{{ansible_user_id}}_{{ansible_date_time.epoch}}"
      state: directory
  
  - name: make_inventory
    local_action:
      module: template
      src: "ansible_hosts.j2"
      dest: "/tmp/ec2_{{ansible_user_id}}_{{ansible_date_time.epoch}}/ansible_hosts"
  
  - name: make_local_hosts_for_os
    local_action:
      module: template
      src: "hosts.j2"
      dest: "/tmp/ec2_{{ ansible_user_id }}_{{ ansible_date_time.epoch }}/hosts"
  
  - name: make_public_hosts_for_os
    local_action:
      module: template
      src: "publichosts.j2"
      dest: "/tmp/ec2_{{ ansible_user_id }}_{{ ansible_date_time.epoch }}/publichosts"
  
  - name: make_ip_list
    local_action:
      module: template
      src: "ips.j2"
      dest: "/tmp/ec2_{{ ansible_user_id }}_{{ ansible_date_time.epoch }}/ips"

  - name: display multiple file contents
    debug:
      var: item
    with_file:
      - "/tmp/ec2_{{ ansible_user_id }}_{{ ansible_date_time.epoch }}/ansible_hosts"
      - "/tmp/ec2_{{ ansible_user_id }}_{{ ansible_date_time.epoch }}/hosts"
      - "/tmp/ec2_{{ ansible_user_id }}_{{ ansible_date_time.epoch }}/publichosts"
      - "/tmp/ec2_{{ ansible_user_id }}_{{ ansible_date_time.epoch }}/ips"

  tags:
    - ec2_create
  vars:
    ansible_python_interpreter: "{{ansible_env.VIRTUAL_ENV}}/bin/python"

# vim: et ts=2 sw=2:
