---
# tasks file for roles/ec2_create

- block:

  - name: create_master
    ec2:
      key_name: "{{ec2_create_key_name}}"
      instance_type: "{{ec2_create_itype}}"
      image: "{{ec2_create_image}}"
      wait: yes
      group: "{{ec2_create_sec_group}}"
      vpc_subnet_id: "{{ec2_create_vpc_subnet}}"
      assign_public_ip: "{{ec2_create_pubip}}"
      region: "{{ec2_region}}"
      exact_count: 1
      instance_tags:
        Name: "{{ec2_master_name}}"
      count_tag:
        Name: "{{ec2_master_name}}"

  - name: create_slaves
    ec2:
      key_name: "{{ec2_create_key_name}}"
      instance_type: "{{ec2_create_itype}}"
      image: "{{ec2_create_image}}"
      wait: yes
      group: "{{ec2_create_sec_group}}"
      vpc_subnet_id: "{{ec2_create_vpc_subnet}}"
      assign_public_ip: "{{ec2_create_pubip}}"
      region: "{{ec2_region}}"
      exact_count: 1
      instance_tags:
        Name: "{{item}}"
      count_tag:
        Name: "{{item}}"
    with_items: "{{ec2_slave_names}}"

  tags:
    - ec2_create
  vars:
    ansible_python_interpreter: "{{ansible_env.VIRTUAL_ENV}}/bin/python"
